/** Код причины, по которой домен отклонил команду. */
export const DOMAIN_ERROR = {
  USERS_ALREADY_EXIST: 'users_already_exist',
  USER_NOT_FOUND: 'user_not_found',
  GITHUB_LOGIN_TAKEN: 'github_login_taken',
  GITHUB_LOGIN_CHAT: 'github_login_chat',
  GITHUB_LOGIN_ACTOR: 'github_login_actor',
  GITHUB_LOGIN_DUPLICATE: 'github_login_duplicate',
  GITHUB_LOGIN_IDEMPOTENCY_KEY: 'github_login_idempotency_key',
  BLANK_NAME: 'blank_name',
  TELEGRAM_USER_ID: 'telegram_user_id',
  REGISTRATION_DUPLICATE: 'registration_duplicate',
  PROJECT_ID_BLANK: 'project_id_blank',
  PROJECT_NAME_BLANK: 'project_name_blank',
  PROJECT_TIMEZONE_BLANK: 'project_timezone_blank',
  PROJECT_CREATED_AT_BLANK: 'project_created_at_blank',
  PROJECT_CREATOR: 'project_creator',
  PROJECT_CHAT: 'project_chat',
  PROJECT_DUPLICATE: 'project_duplicate',
  PROJECT_IDEMPOTENCY_KEY: 'project_idempotency_key',
  CHAT_ID_BLANK: 'chat_id_blank',
  CHAT_TIMEZONE_BLANK: 'chat_timezone_blank',
  CHAT_NOT_SUPERGROUP: 'chat_not_supergroup',
  CHAT_IS_TOPIC: 'chat_is_topic',
  CHAT_ADMIN_RIGHTS: 'chat_admin_rights',
  CHAT_BIND_ACTOR: 'chat_bind_actor',
  CHAT_PROJECT_MISSING: 'chat_project_missing',
  CHAT_ALREADY_BOUND: 'chat_already_bound',
  CHAT_DUPLICATE: 'chat_duplicate',
  CHAT_IDEMPOTENCY_KEY: 'chat_idempotency_key',
  REPORTS_TOPIC_ID: 'reports_topic_id',
  PROJECT_MEMBER_ID_BLANK: 'project_member_id_blank',
  PROJECT_MEMBER_PROJECT_BLANK: 'project_member_project_blank',
  PROJECT_MEMBER_USER_BLANK: 'project_member_user_blank',
  PROJECT_ROLE: 'project_role',
  MEMBER_CHAT: 'member_chat',
  MEMBER_ACTOR: 'member_actor',
  MEMBER_ACCESS: 'member_access',
  MEMBER_PROJECT_MISSING: 'member_project_missing',
  MEMBER_PROJECT_AMBIGUOUS: 'member_project_ambiguous',
  MEMBER_NOT_CANDIDATE: 'member_not_candidate',
  MEMBER_ALREADY: 'member_already',
  MEMBER_ABSENT: 'member_absent',
  MEMBER_DUPLICATE: 'member_duplicate',
  MEMBER_IDEMPOTENCY_KEY: 'member_idempotency_key',
  ACCESS_IDEMPOTENCY_KEY: 'access_idempotency_key',
  ACCESS_UPDATE_KIND: 'access_update_kind',
  TOPIC_CHAT: 'topic_chat',
  TOPIC_ACTOR: 'topic_actor',
  TOPIC_ACCESS: 'topic_access',
  TOPIC_PROJECT_MISSING: 'topic_project_missing',
  TOPIC_PROJECT_AMBIGUOUS: 'topic_project_ambiguous',
  TOPIC_UNBOUND: 'topic_unbound',
  TOPIC_ABSENT: 'topic_absent',
  TOPIC_AMBIGUOUS: 'topic_ambiguous',
  TOPIC_ID: 'topic_id',
  TOPIC_ALREADY: 'topic_already',
  TOPIC_DUPLICATE: 'topic_duplicate',
  TOPIC_IDEMPOTENCY_KEY: 'topic_idempotency_key',
  REPORTS_TOPIC_CHAT: 'reports_topic_chat',
  REPORTS_TOPIC_ACTOR: 'reports_topic_actor',
  REPORTS_TOPIC_ROOT: 'reports_topic_root',
  REPORTS_TOPIC_ACCESS: 'reports_topic_access',
  REPORTS_TOPIC_PROJECT_MISSING: 'reports_topic_project_missing',
  REPORTS_TOPIC_PROJECT_AMBIGUOUS: 'reports_topic_project_ambiguous',
  REPORTS_TOPIC_UNBOUND: 'reports_topic_unbound',
  REPORTS_TOPIC_ALREADY: 'reports_topic_already',
  REPORTS_TOPIC_COLLIDES: 'reports_topic_collides',
  REPORTS_TOPIC_DUPLICATE: 'reports_topic_duplicate',
  REPORTS_TOPIC_IDEMPOTENCY_KEY: 'reports_topic_idempotency_key',
  SCHEDULE_CHAT: 'schedule_chat',
  SCHEDULE_ACTOR: 'schedule_actor',
  SCHEDULE_ACCESS: 'schedule_access',
  SCHEDULE_ROOT: 'schedule_root',
  SCHEDULE_CLEAR: 'schedule_clear',
  SCHEDULE_PROJECT_MISSING: 'schedule_project_missing',
  SCHEDULE_PROJECT_AMBIGUOUS: 'schedule_project_ambiguous',
  SCHEDULE_UNBOUND: 'schedule_unbound',
  SCHEDULE_TIME_BLANK: 'schedule_time_blank',
  SCHEDULE_TIMEZONE_BLANK: 'schedule_timezone_blank',
  SCHEDULE_DUPLICATE: 'schedule_duplicate',
  SCHEDULE_IDEMPOTENCY_KEY: 'schedule_idempotency_key',
  SETTINGS_CHAT: 'settings_chat',
  SETTINGS_ACTOR: 'settings_actor',
  SETTINGS_ACCESS: 'settings_access',
  SETTINGS_PROJECT_MISSING: 'settings_project_missing',
  SETTINGS_PROJECT_AMBIGUOUS: 'settings_project_ambiguous',
  SETTINGS_TIMEZONE: 'settings_timezone',
  SETTINGS_CHAT_UNKNOWN: 'settings_chat_unknown',
  SETTINGS_MEMBER_ABSENT: 'settings_member_absent',
  SETTINGS_MEMBER_AMBIGUOUS: 'settings_member_ambiguous',
  SETTINGS_DUPLICATE: 'settings_duplicate',
  SETTINGS_IDEMPOTENCY_KEY: 'settings_idempotency_key',
  REPOSITORY_ID: 'repository_id',
  REPOSITORY_OWNER_BLANK: 'repository_owner_blank',
  REPOSITORY_NAME_BLANK: 'repository_name_blank',
  REPOSITORY_CHAT: 'repository_chat',
  REPOSITORY_ACCESS: 'repository_access',
  REPOSITORY_APP: 'repository_app',
  REPOSITORY_UNAVAILABLE: 'repository_unavailable',
  REPOSITORY_IDEMPOTENCY_KEY: 'repository_idempotency_key',
  REPOSITORY_IDENTITY: 'repository_identity',
  PROJECT_REPOSITORY_CHAT: 'project_repository_chat',
  PROJECT_REPOSITORY_ACTOR: 'project_repository_actor',
  PROJECT_REPOSITORY_ACCESS: 'project_repository_access',
  PROJECT_REPOSITORY_PROJECT_MISSING: 'project_repository_project_missing',
  PROJECT_REPOSITORY_PROJECT_AMBIGUOUS: 'project_repository_project_ambiguous',
  PROJECT_REPOSITORY_ID: 'project_repository_id',
  PROJECT_REPOSITORY_UNKNOWN: 'project_repository_unknown',
  PROJECT_REPOSITORY_ALREADY: 'project_repository_already',
  PROJECT_REPOSITORY_DUPLICATE: 'project_repository_duplicate',
  PROJECT_REPOSITORY_IDEMPOTENCY_KEY: 'project_repository_idempotency_key',
  PROJECT_REPOSITORY_CHANGE_ACTOR: 'project_repository_change_actor',
  PROJECT_REPOSITORY_NOT_CONNECTED: 'project_repository_not_connected',
  PROJECT_REPOSITORY_CHANGE_DUPLICATE: 'project_repository_change_duplicate',
} as const;

export type DomainErrorCode = (typeof DOMAIN_ERROR)[keyof typeof DOMAIN_ERROR];

/** Ошибка домена с кодом причины. Сообщение — для журнала, решение принимает код. */
export class DomainError extends Error {
  readonly code: DomainErrorCode;

  constructor(code: DomainErrorCode, message: string) {
    super(message);
    this.name = 'DomainError';
    this.code = code;
  }
}
